name: Markdown Pandoc PDF generator
on: [push]

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      
      - name: Install Pandoc
        uses: pandoc/actions/setup@v1
        with:
          version: 2.19
      
      - name: Install texlive
        uses: teatimeguest/setup-texlive-action@v3
        with:
          packages: |
            scheme-full
            collection-mathscience
            hyperref
            microtype
            koma-script
            setspace
            xcolor
            adjustbox
            fancyvrb
            booktabs
            texliveonfly
            tex-gyre
            tipa

      - name: Generate the pdf
        run: make

      - name: Archive pdf 
        uses: actions/upload-artifact@v4
        with:
          name: markdown-pandoc-pdf
          path: build/report.pdf
